.PHONY: help lint lint-tasks lint-tasks-freshness lint-tasks-rule9 test test-all test-force check audit install-deps count clean fmt coverage

.DEFAULT_GOAL := help

# All scripts to lint
# Endpoint-security shims (curl/jq/grep/...) are Mach-O binaries/symlinks.
# Shellcheck only the real scripts under bin/.
BIN_SCRIPTS := $(shell for f in bin/*; do \
  file -b "$$f" 2>/dev/null | grep -qE 'shell script|POSIX shell script' && echo "$$f"; \
done)

SCRIPTS := macos.sh macos-visual.sh macos-apps.sh snapshot.sh \
           $(wildcard private_dot_agent-browser/executable_*.sh) \
           lib/agentbrew-memory-readiness.sh lib/brew-bottle-audit.sh lib/colors.sh lib/lock.sh lib/output.sh lib/overlay-locate.sh lib/secret-scan.sh lib/stats.sh \
           $(BIN_SCRIPTS) $(wildcard modules/*/doctor.sh) \
           $(wildcard .chezmoiscripts/*.sh) $(wildcard .github/scripts/*.sh) \
           $(shell grep -L call_lefthook git-hooks/* 2>/dev/null)
# git-hooks/: lint only HAND-WRITTEN hooks (commit-msg, post-commit). The
# pre-commit / pre-push / post-merge / post-rewrite shims are GENERATED by
# `lefthook install` and ship a `[ "$X" = "1" -o "$X" = "true" ]` line that
# trips SC2166 — we don't control lefthook's codegen, so we don't lint it.
# `grep -L call_lefthook` selects the non-shim hooks and self-adapts as the
# generated shim set changes.

# macOS interactive scheduling tier — all child processes inherit
FULLPOWER := $(shell command -v taskpolicy >/dev/null 2>&1 && echo "taskpolicy -t 0 -l 0" || echo "")

DEV_DEPS := shellcheck bats-core parallel chezmoi fd jq
# python3 is bundled with macOS / GitHub Actions runners; we use it via
# bin/dotfiles-coverage instead of kcov because kcov 43 produces empty
# coverage on macOS Tahoe (DYLD_INSERT_LIBRARIES blocked by SIP).
OPTIONAL_DEV_DEPS := shfmt
TASKS_LINT_VERSION := $(shell sed -n '1p' .tasks-lint-version)
TASKS_LINT := npx -y @tasks-md/lint@$(TASKS_LINT_VERSION)
TASKS_FILE ?= TASKS.md

# ── Help ─────────────────────────────────────────────────────────────
help: ## Show this help message
	@printf "\033[1mUsage:\033[0m make [target]\n\n"
	@printf "\033[1mTargets:\033[0m\n"
	@grep -E '^[a-zA-Z_-]+:.*##' $(MAKEFILE_LIST) | \
		awk -F ':.*## ' '{printf "  \033[36m%-14s\033[0m %s\n", $$1, $$2}'

# ── Lint: shellcheck all scripts ─────────────────────────────────────
lint: ## Shellcheck all scripts
	@echo "═══ Shellcheck ═══"
	@$(FULLPOWER) shellcheck -S warning $(SCRIPTS) && echo "✓ All scripts pass shellcheck" || exit 1

# ── Lint: task queue format ──────────────────────────────────────────
lint-tasks: ## Validate TASKS.md queue format
	@echo "═══ TASKS.md lint ═══"
	@$(TASKS_LINT) $(TASKS_FILE)
	@echo "═══ tasks-stability priority ═══"
	@.github/scripts/check-tasks-stability.sh
	@echo "═══ tasks-rule9 fields ═══"
	@TASKS_RULE9_FILE="$(TASKS_FILE)" .github/scripts/check-tasks-rule9-fields.sh

# ── Lint: tasks-md/lint pin freshness (advisory, never fails) ────────
lint-tasks-freshness: ## Warn if .tasks-lint-version is behind npm
	@echo "═══ tasks-lint freshness ═══"
	@.github/scripts/check-tasks-lint-freshness.sh

# ── Lint: rule-9 fields on P0/P1 ─────────────────────────────────────
# Walks TASKS.md and fails when any P0/P1 entry lacks one of the 5
# Hypothesis-Driven-Development fields (Hypothesis/Success/Pivot/
# Measurement/Anchor).
lint-tasks-rule9: ## Fail when P0/P1 tasks lack the 5 rule-9 fields
	@echo "═══ tasks-rule9 fields ═══"
	@TASKS_RULE9_FILE="$(TASKS_FILE)" .github/scripts/check-tasks-rule9-fields.sh

# ── Test: affected tests only (cached — skips if tree unchanged) ─────
# JOBS = number of parallel test files. Within-file parallelism is OFF by
# default (--no-parallelize-within-files) because some test files (e.g.
# dotfiles-profile.bats) share chezmoi state and would corrupt each other
# under concurrent execution. Slow files that ARE safe to parallelize opt
# in by setting `unset BATS_NO_PARALLELIZE_WITHIN_FILE` in their setup_file().
# Currently opted in: doctor.bats (was 826s serial), morning.bats (280s).
JOBS ?= $(shell sysctl -n hw.ncpu 2>/dev/null || nproc 2>/dev/null || echo 4)
test: ## Run affected tests only (cached, git-aware)
	@affected=$$(./bin/bats-affected); \
	if [ -z "$$affected" ]; then \
	  echo "✓ No affected test files (nothing changed)"; \
	else \
	  count=$$(echo "$$affected" | wc -l | tr -d ' '); \
	  echo "═══ Tests: $$count affected file(s) ($(JOBS) jobs) ═══"; \
	  echo "$$affected" | xargs $(FULLPOWER) cached-run bats --jobs $(JOBS) --no-parallelize-within-files; \
	fi

test-all: ## Run full test suite (cached)
	@$(FULLPOWER) cached-run bats --jobs $(JOBS) --no-parallelize-within-files tests/

test-force: ## Run full test suite (no cache)
	@echo "═══ Tests ($(JOBS) parallel jobs) ═══"
	@$(FULLPOWER) bats --jobs $(JOBS) --no-parallelize-within-files tests/

# ── Check: lint + task queue lint + test ─────────────────────────────
check: lint lint-tasks test ## Lint + task queue lint + test (run before committing)
	@echo ""
	@echo "✓ All checks passed"

audit: ## Run security and repo-hygiene audit
	@./bin/dotfiles-audit

# ── Install development dependencies ─────────────────────────────────
install-deps: ## Install required dev tools plus fmt/coverage helpers
	brew install $(DEV_DEPS) $(OPTIONAL_DEV_DEPS)

# ── Count: show live stats (never copy them into docs) ──
count: ## Show test, module, and check counts
	@tests=$$(bats --count tests/*.bats 2>/dev/null | awk '{s+=$$1}END{print s}'); \
	files=$$(ls tests/*.bats 2>/dev/null | wc -l | tr -d ' '); \
	modules=$$(ls -d modules/*/doctor.sh 2>/dev/null | wc -l | tr -d ' '); \
	checks=$$(grep -rhc '^\s*check' modules/*/doctor.sh 2>/dev/null | awk '{s+=$$1}END{print s}'); \
	macos_total=$$(jq 'length' data/macos-defaults.json); \
	macos_core=$$(jq '[.[] | select(.script == "core")] | length' data/macos-defaults.json); \
	macos_visual=$$(jq '[.[] | select(.script == "visual")] | length' data/macos-defaults.json); \
	macos_apps=$$(jq '[.[] | select(.script == "apps")] | length' data/macos-defaults.json); \
	printf "Tests:   %s across %s bats files\n" "$$tests" "$$files"; \
	printf "Modules: %s\n" "$$modules"; \
	printf "Checks:  %s\n" "$$checks"; \
	printf "macOS defaults: %s total (%s core, %s visual, %s apps)\n" "$$macos_total" "$$macos_core" "$$macos_visual" "$$macos_apps"

# ── Clean: remove test artifacts and caches ──────────────────────────
clean: ## Remove test cache and tmp artifacts
	@rm -rf .bats-run-cache/
	@rm -rf tmp/ .tmp/
	@rm -rf coverage/
	@echo "✓ Cleaned test cache and artifacts"

# ── Format: auto-format shell scripts with shfmt ─────────────────────
fmt: ## Format shell scripts (requires shfmt)
	@if command -v shfmt >/dev/null 2>&1; then \
	  shfmt -w -i 2 -ci bin/ lib/ modules/ macos.sh macos-visual.sh macos-apps.sh snapshot.sh 2>/dev/null; \
	  echo "✓ Formatted shell scripts with shfmt"; \
	else \
	  echo "shfmt not found — install with: brew install shfmt"; \
	fi

# ── Coverage: run tests with custom shell-trace harness ──────────────
# We use bin/dotfiles-coverage (a portable BASH_ENV-based harness) instead
# of kcov because kcov 43 produces empty coverage.json on macOS Tahoe (SIP
# blocks the DYLD_INSERT_LIBRARIES dance kcov needs to follow bats's `bash
# CMD` subprocesses). The harness works on Linux CI and macOS local dev.
# See docs/ci-setup.md for the full rationale.
coverage: ## Run tests with line coverage (uses bin/dotfiles-coverage)
	@bin/dotfiles-coverage run tests/
	@echo ""
	@.github/scripts/check-shell-coverage.sh coverage/bats/coverage.json .shell-coverage-floor
