#!/usr/bin/env bats
# Focused tests for lib/strip-agent-attribution.sh.

LIB="$BATS_TEST_DIRNAME/../lib/strip-agent-attribution.sh"

setup() {
  TEST_DIR="$(mktemp -d)"
  MSG_FILE="$TEST_DIR/message.txt"
  unset MINSKY_PIPELINE
}

teardown() {
  rm -rf "$TEST_DIR"
}

write_msg() {
  printf '%s' "$1" > "$MSG_FILE"
}

strip_stream_text() {
  local input="$1"
  run bash -c '. "$1"; printf "%s" "$2" | _strip_agent_attribution_in_stream' _ "$LIB" "$input"
}

strip_stream_text_minsky() {
  local input="$1"
  run env MINSKY_PIPELINE=1 bash -c '. "$1"; printf "%s" "$2" | _strip_agent_attribution_in_stream' _ "$LIB" "$input"
}

strip_file() {
  . "$LIB"
  _strip_agent_attribution_in_file "$MSG_FILE" > "$TEST_DIR/strip.out"
}

strip_file_minsky() {
  . "$LIB"
  MINSKY_PIPELINE=1 _strip_agent_attribution_in_file "$MSG_FILE" > "$TEST_DIR/strip.out"
}

footer_count_in_output() {
  printf '%s' "$output" | grep -c "Written by an agent, not Fyodor" || true
}

footer_count_in_file() {
  grep -c "Written by an agent, not Fyodor" "$MSG_FILE" || true
}

@test "stream mode strips known vendor footers and appends Fyodor footer" {
  strip_stream_text $'## Why this is needed\nKeeps public attribution neutral.\n\nGenerated with [Devin](https://cli.devin.ai/docs)\nCo-Authored-By: Claude <noreply@anthropic.com>\nCo-Authored-By: Cursor <agent@cursor.com>'

  [ "$status" -eq 0 ]
  [[ "$output" == *"Keeps public attribution neutral."* ]]
  [[ "$output" != *"Generated with [Devin]"* ]]
  [[ "$output" != *"Co-Authored-By: Claude"* ]]
  [[ "$output" != *"Co-Authored-By: Cursor"* ]]
  [[ "$output" == *"Written by an agent, not Fyodor"* ]]
  [ "$(footer_count_in_output)" = "1" ]
}

@test "stream mode is idempotent when Fyodor footer already exists" {
  strip_stream_text $'Body.\n\nGenerated with [Claude Code](https://claude.com/code)\n\n---\n_🤖 Written by an agent, not Fyodor. Ping me if this looks off._'

  [ "$status" -eq 0 ]
  [[ "$output" != *"Generated with [Claude Code]"* ]]
  [ "$(footer_count_in_output)" = "1" ]
}

@test "stream mode trims trailing blank lines without adding footer to clean text" {
  strip_stream_text $'Human-authored body with no vendor attribution.\n   \n\t'

  [ "$status" -eq 0 ]
  [ "$output" = "Human-authored body with no vendor attribution." ]
  [[ "$output" != *"Written by an agent"* ]]
}

@test "stream mode bypasses stripping when MINSKY_PIPELINE is set" {
  local input
  input=$'Body.\n\nGenerated with [Devin](https://cli.devin.ai/docs)'

  strip_stream_text_minsky "$input"

  [ "$status" -eq 0 ]
  [ "$output" = "$input" ]
  [[ "$output" != *"Written by an agent, not Fyodor"* ]]
}

@test "file mode strips vendor trailers, preserves human trailers, and appends Fyodor footer" {
  write_msg $'feat: add guarded wrapper\n\nCo-Authored-By: Alice Smith <alice@example.com>\nCo-Authored-By: Devin <158242+devin-ai-integration[bot]@users.noreply.github.com>\nGenerated by [Windsurf](https://windsurf.com)'

  strip_file

  [ "$(grep -c "Co-Authored-By: Alice Smith" "$MSG_FILE")" = "1" ]
  [ "$(grep -c "devin-ai-integration" "$MSG_FILE" || true)" = "0" ]
  [ "$(grep -c "Generated by \\[Windsurf\\]" "$MSG_FILE" || true)" = "0" ]
  [ "$(footer_count_in_file)" = "1" ]
}

@test "file mode is idempotent and does not duplicate Fyodor footer" {
  write_msg $'feat: add guarded wrapper\n\nGenerated with [Devin](https://cli.devin.ai/docs)\n\n---\n_🤖 Written by an agent, not Fyodor. Ping me if this looks off._\n'

  strip_file
  strip_file

  [ "$(grep -c "Generated with \\[Devin\\]" "$MSG_FILE" || true)" = "0" ]
  [ "$(footer_count_in_file)" = "1" ]
}

@test "file mode trims trailing blanks before appending Fyodor footer" {
  write_msg $'feat: add guarded wrapper\n\nGenerated with [Devin](https://cli.devin.ai/docs)\n\n\n'

  strip_file

  local content
  content="$(cat "$MSG_FILE")"
  [[ "$content" != *$'\n\n\n---'* ]]
  [[ "$content" == *$'\n\n---\n_🤖 Written by an agent, not Fyodor. Ping me if this looks off._' ]]
}

@test "file mode leaves merge and fixup messages unchanged" {
  write_msg $'Merge branch feature/foo\n\nGenerated with [Devin](https://cli.devin.ai/docs)\n'
  strip_file
  [ "$(grep -c "Generated with \\[Devin\\]" "$MSG_FILE")" = "1" ]
  [ "$(footer_count_in_file)" = "0" ]

  write_msg $'fixup! feat: add guarded wrapper\n\nCo-Authored-By: Devin <devin-ai-integration[bot]@users.noreply.github.com>\n'
  strip_file
  [ "$(grep -c "Co-Authored-By: Devin" "$MSG_FILE")" = "1" ]
  [ "$(footer_count_in_file)" = "0" ]
}

@test "file mode with MINSKY_PIPELINE preserves the orchestrator's message unchanged" {
  # Note: no trailing newline because `$(cat ...)` strips it; we want the
  # comparison to be honest about whether the library altered bytes.
  local input=$'feat: add guarded wrapper\n\nGenerated with [Devin](https://cli.devin.ai/docs)\nCo-Authored-By: Claude <noreply@anthropic.com>'
  write_msg "$input"

  strip_file_minsky

  # Pure bypass: the orchestrator's message survives byte-for-byte.
  [ "$(cat "$MSG_FILE")" = "$input" ]
  # No tool-named trailer is injected by the library.
  [ "$(grep -c "Co-Authored-By: Minsky" "$MSG_FILE" || true)" = "0" ]
  [ "$(grep -c "Generated by Minsky" "$MSG_FILE" || true)" = "0" ]
  [ "$(footer_count_in_file)" = "0" ]
}
